name: Continuous Integration
 
on: 
  pull_request:
    branches:
      - main
    paths-ignore: ["README.md"]
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
    services:
      postgres:
        image: postgres:14.3-alpine
        env:
          POSTGRES_DB: dicoding_forum_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate up
        npm run test
      env:
        CI: true
        PGHOST_TEST: postgres
        PGUSER_TEST: postgres
        PGDATABASE_TEST: dicoding_forum_test
        PGPASSWORD_TEST: password
        PGPORT_TEST: 5432
        PGHOST: postgres
        PGUSER: postgres
        PGDATABASE: dicoding_forum_test
        PGPASSWORD: password
        PGPORT: 5432
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
        ACCCESS_TOKEN_AGE: 3000